name: style check


on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8, 3.9]
        steps:
            - uses: actions/checkout@v2
            - name: Install python dependencies
              run: |
                python3 -m pip install --upgrade pip black==22.3.0 flake8==3.9.2
            - name: Run flake8
              shell: bash
              working-directory: ${{github.workspace}}
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --show-source --statistics
                flake8 .
            - name: Run python black
              shell: bash
              working-directory: ${{github.workspace}}
              run: |
                black --check --diff .

